### ISSUE TITLE
Not working with Crystal 0.24.1

### ISSUE THREAD

**Issue by bararchy** [TechMagister/cracker#11]

**Comment by bentranter** [comment]
I'm assuming this is to track the compilation error that occurs when using Crystal 0.24.1 to build:

```
Error in src/cracker.cr:2: while requiring "cli"

require "cli"
^

in lib/cli/src/cli.cr:1: while requiring "./lib"

require "./lib"
^

in lib/cli/src/lib.cr:7: while requiring "./lib/*"

require "./lib/*"
^

in lib/cli/src/lib/ios.cr:1: while requiring "./ios/*"

require "./ios/*"
^

in lib/cli/src/lib/ios/pipe.cr:10: IO is not a module, it's a class

    include IO
            ^~
```
This seems to be fixed by https://github.com/mosop/cli/pull/10, so once that's merged and `shard.yml` points to the latest `mosop/cli` release, this should be fixed.

**Comment by TechMagister** [comment]
Thanks for your feedback 👍 , I'll follow the PR to fix this asap.

**Comment by ghost** [comment]
Unfortunately `mosop/cli` seems to be abandoned, the owner last activity on github was on october.
For now I think it's better to use an updated fork like `Jens0512/cli`.
